version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: dt-1229
    depends_on:
      - db
    expose:
      - "9000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ../backend:/var/www/backend
      - ../frontend:/var/www/frontend
    depends_on:
      - backend
      - phpmyadmin
      - frontend 

volumes:
  db_data:
